### ISSUE TITLE
Add Audiobooks tests

### ISSUE THREAD

**Issue by FC5570** [spotifyts/spotify.ts#114]
Currently, audibooks are only available in the US, so I am not able to access any to get the ID and test. If anyone is willing to write tests for the Audiobooks, please comment here and I will assign you.

Take a look at [tests](https://github.com/spotifyts/spotify.ts/tree/main/tests) to familiarize yourself with the code. Then create a similar test for both the manager's functions (`fetch` and `fetchSeveral`)

**Comment by prashanthr** [comment]
Hi @FC5570, I can help out with this issue.

Some background: I've previously used and spent enough time using the unofficial NodeJS based spotify wrapper - https://github.com/thelinmichael/spotify-web-api-node. 

You can assign this to me and I'll open a PR to add these tests. Thanks.
